<a href="https://colab.research.google.com/github/wadaglizz/DSA4060-Week3-667468/blob/main/wk4asg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
movies = pd.DataFrame({
    "movie_id": [1,2,3,4,5,6,7,8,9,10],
    "title": [
        "Galaxy Mission",
        "Love in Nairobi",
        "Final Battle",
        "Family Weekend",
        "Future World",
        "Broken Hearts",
        "City Detectives",
        "Space Warriors",
        "Wedding Weekend",
        "Hidden Truth"
    ],
    "Action":  [1,0,1,0,1,0,1,1,0,0],
    "Comedy":  [0,0,0,1,0,0,0,0,1,0],
    "Drama":   [0,1,0,0,0,1,1,0,0,1],
    "Romance": [0,1,0,0,0,1,0,0,1,0],
    "SciFi":   [1,0,0,0,1,0,0,1,0,0]
})

movies

   movie_id            title  Action  Comedy  Drama  Romance  SciFi
0         1   Galaxy Mission       1       0      0        0      1
1         2  Love in Nairobi       0       0      1        1      0
2         3     Final Battle       1       0      0        0      0
3         4   Family Weekend       0       1      0        0      0
4         5     Future World       1       0      0        0      1
5         6    Broken Hearts       0       0      1        1      0
6         7  City Detectives       1       0      1        0      0
7         8   Space Warriors       1       0      0        0      1
8         9  Wedding Weekend       0       1      0        1      0
9        10     Hidden Truth       0       0      1        0      0

In [3]:
movies.head()

   movie_id            title  Action  Comedy  Drama  Romance  SciFi
0         1   Galaxy Mission       1       0      0        0      1
1         2  Love in Nairobi       0       0      1        1      0
2         3     Final Battle       1       0      0        0      0
3         4   Family Weekend       0       1      0        0      0
4         5     Future World       1       0      0        0      1

In [4]:
movies.shape

(10, 7)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  10 non-null     int64
 1   title     10 non-null     object
 2   Action    10 non-null     int64
 3   Comedy    10 non-null     int64
 4   Drama     10 non-null     int64
 5   Romance   10 non-null     int64
 6   SciFi     10 non-null     int64
dtypes: int64(6), object(1)
memory usage: 692.0+ bytes

there are ten movies in the dataset

there are 5 genres in rhe datset action,
comedy, drama, romance and scifi

A row contains data about a specific movie such as id and title

In [6]:
features = ["Action", "Comedy", "Drama", "Romance", "SciFi"]

movie_features = movies[features]

movie_features

   Action  Comedy  Drama  Romance  SciFi
0       1       0      0        0      1
1       0       0      1        1      0
2       1       0      0        0      0
3       0       1      0        0      0
4       1       0      0        0      1
5       0       0      1        1      0
6       1       0      1        0      0
7       1       0      0        0      1
8       0       1      0        1      0
9       0       0      1        0      0

THE 1s mean the movie is either action or scifi while o represents drama comedy and romance

In [8]:
movies.loc[movies["title"] == "Galaxy Mission"]

   movie_id           title  Action  Comedy  Drama  Romance  SciFi
0         1  Galaxy Mission       1       0      0        0      1

In [9]:
ratings = pd.DataFrame({
    "movie_id": [1, 2, 3, 5],
    "rating": [5, 2, 4, 5]
})

ratings

   movie_id  rating
0         1       5
1         2       2
2         3       4
3         5       5

In [10]:
user_movies = ratings.merge(
    movies,
    on="movie_id"
)

user_movies

   movie_id  rating            title  Action  Comedy  Drama  Romance  SciFi
0         1       5   Galaxy Mission       1       0      0        0      1
1         2       2  Love in Nairobi       0       0      1        1      0
2         3       4     Final Battle       1       0      0        0      0
3         5       5     Future World       1       0      0        0      1

In [11]:
user_movies[
    ["title", "rating", "Action", "Comedy", "Drama", "Romance", "SciFi"]
]

             title  rating  Action  Comedy  Drama  Romance  SciFi
0   Galaxy Mission       5       1       0      0        0      1
1  Love in Nairobi       2       0       0      1        1      0
2     Final Battle       4       1       0      0        0      0
3     Future World       5       1       0      0        0      1

User A appears to prefer Action and SciFi movies, because they gave high ratings to Galaxy Mission and Future World,
They also rated Final Battle highly, which contains Action. The low rating for Love in Nairobi, which contains Drama and Romance, suggests weaker interest in those genres.

In [12]:
rated_features = user_movies[features]
user_ratings = user_movies["rating"]

rated_features

   Action  Comedy  Drama  Romance  SciFi
0       1       0      0        0      1
1       0       0      1        1      0
2       1       0      0        0      0
3       1       0      0        0      1

In [13]:
user_ratings

0    5
1    2
2    4
3    5
Name: rating, dtype: int64

In [14]:
weighted_features = rated_features.mul(
    user_ratings,
    axis=0
)

weighted_features

   Action  Comedy  Drama  Romance  SciFi
0       5       0      0        0      5
1       0       0      2        2      0
2       4       0      0        0      0
3       5       0      0        0      5

In [15]:
user_profile = weighted_features.sum()

user_profile

Action     14
Comedy      0
Drama       2
Romance     2
SciFi      10
dtype: int64

The user's strongest preferences are Action and SciFi.

Action has a profile score of 14.

SciFi has a profile score of 10.

In [16]:
user_profile_normalized = (
    user_profile / user_profile.sum()
)

user_profile_normalized

Action     0.500000
Comedy     0.000000
Drama      0.071429
Romance    0.071429
SciFi      0.357143
dtype: float64

In [17]:
movies["recommendation_score"] = (
    movie_features
    .mul(user_profile_normalized)
    .sum(axis=1)
)

movies[["title", "recommendation_score"]]

             title  recommendation_score
0   Galaxy Mission              0.857143
1  Love in Nairobi              0.142857
2     Final Battle              0.500000
3   Family Weekend              0.000000
4     Future World              0.857143
5    Broken Hearts              0.142857
6  City Detectives              0.571429
7   Space Warriors              0.857143
8  Wedding Weekend              0.071429
9     Hidden Truth              0.071429

In [18]:
ranked_movies = movies.sort_values(
    "recommendation_score",
    ascending=False
)

ranked_movies[
    ["title", "recommendation_score"]
]

             title  recommendation_score
0   Galaxy Mission              0.857143
4     Future World              0.857143
7   Space Warriors              0.857143
6  City Detectives              0.571429
2     Final Battle              0.500000
1  Love in Nairobi              0.142857
5    Broken Hearts              0.142857
8  Wedding Weekend              0.071429
9     Hidden Truth              0.071429
3   Family Weekend              0.000000

In [19]:
watched_movies = ratings["movie_id"]

recommendations = ranked_movies[
    ~ranked_movies["movie_id"].isin(watched_movies)
]

recommendations[
    ["title", "recommendation_score"]
]

             title  recommendation_score
7   Space Warriors              0.857143
6  City Detectives              0.571429
5    Broken Hearts              0.142857
8  Wedding Weekend              0.071429
9     Hidden Truth              0.071429
3   Family Weekend              0.000000

In [20]:
top_3 = recommendations[
    ["title", "recommendation_score"]
].head(3)

top_3

             title  recommendation_score
7   Space Warriors              0.857143
6  City Detectives              0.571429
5    Broken Hearts              0.142857

RECOMMENDATION BREAKDOWN

Space Warriors is recommended because it contains both Action and
SciFi, which are User A's two strongest preferences.

City Detectives is recommended because it contains Action, which is
the user's strongest individual preference.

Hidden Truth receives a smaller positive score because it contains
Drama, which is a relatively weak preference for User A.

In [21]:
def recommend_movies(movies, ratings, features, n=3):
    user_movies = ratings.merge(
        movies,
        on="movie_id"
    )

    rated_features = user_movies[features]

    weighted_features = rated_features.mul(
        user_movies["rating"],
        axis=0
    )

    user_profile = weighted_features.sum()

    user_profile = user_profile / user_profile.sum()

    scores = (
        movies[features]
        .mul(user_profile)
        .sum(axis=1)
    )

    results = movies.copy()

    results["recommendation_score"] = scores

    watched = ratings["movie_id"]

    results = results[
        ~results["movie_id"].isin(watched)
    ]

    return results.sort_values(
        "recommendation_score",
        ascending=False
    ).head(n)

In [22]:
recommend_movies(
    movies,
    ratings,
    features
)

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
7,8,Space Warriors,1,0,0,0,1,0.857143
6,7,City Detectives,1,0,1,0,0,0.571429
5,6,Broken Hearts,0,0,1,1,0,0.142857

In [23]:
user_b_ratings = pd.DataFrame({
    "movie_id": [2, 4, 6, 9],
    "rating": [5, 4, 5, 4]
})

recommend_movies(
    movies,
    user_b_ratings,
    features
)

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
9,10,Hidden Truth,0,0,1,0,0,0.3125
6,7,City Detectives,1,0,1,0,0,0.3125
2,3,Final Battle,1,0,0,0,0,0.0000

User A and User B receive different recommendations because their ratings
produce different user preference profiles.

User A strongly prefers Action and SciFi, while User B strongly prefers
Romance, Drama, and Comedy.

Since recommendation scores are calculated from these profiles, movies containing the preferred features receive higher scores
for each user.

In [24]:
new_movie = {
    "movie_id": 11,
    "title": "Coastal Mystery",
    "Action": 0,
    "Comedy": 0,
    "Drama": 1,
    "Romance": 0,
    "SciFi": 0
}

movies = pd.concat(
    [movies, pd.DataFrame([new_movie])],
    ignore_index=True
)

movies

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
0,1,Galaxy Mission,1,0,0,0,1,0.857143
1,2,Love in Nairobi,0,0,1,1,0,0.142857
2,3,Final Battle,1,0,0,0,0,0.500000
3,4,Family Weekend,0,1,0,0,0,0.000000
4,5,Future World,1,0,0,0,1,0.857143
5,6,Broken Hearts,0,0,1,1,0,0.142857
6,7,City Detectives,1,0,1,0,0,0.571429
7,8,Space Warriors,1,0,0,0,1,0.857143
8,9,Wedding Weekend,0,1,0,1,0,0.071429
9,10,Hidden Truth,0,0,1,0,0,0.071429
10,11,Coastal Mystery,0,0,1,0,0,NaN

In [25]:
my_user = pd.DataFrame({
    "movie_id": [1, 3, 6, 9],
    "rating": [5, 4, 2, 3]
})

recommend_movies(
    movies,
    my_user,
    features,
    n=5
)

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
4,5,Future World,1,0,0,0,1,0.583333
7,8,Space Warriors,1,0,0,0,1,0.583333
6,7,City Detectives,1,0,1,0,0,0.458333
1,2,Love in Nairobi,0,0,1,1,0,0.291667
3,4,Family Weekend,0,1,0,0,0,0.125000

action has a strong score of 9 while romance has a score of 5

In [26]:
my_recommendations = recommend_movies(
    movies,
    my_user,
    features,
    n=5
)

my_recommendations

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
4,5,Future World,1,0,0,0,1,0.583333
7,8,Space Warriors,1,0,0,0,1,0.583333
6,7,City Detectives,1,0,1,0,0,0.458333
1,2,Love in Nairobi,0,0,1,1,0,0.291667
3,4,Family Weekend,0,1,0,0,0,0.125000

future world space warriors and city detectives have the highest recommendation scores

future world ranks first because its feature combination has the greatest overlap with the user's strongest preferences.

The model ignores information such as:

Actors

Directors

Release year

Language

28

No. Two users who watched the same movies can receive different
recommendations if they gave different ratings.

The model uses ratings to weight the features of each movie when constructing
the user preference profile. Therefore, different ratings produce different
feature preference scores. A user who gives high ratings to Action and SciFi
movies will receive higher scores for Action/SciFi candidates, while a user
who gives high ratings to Drama and Romance movies will receive higher scores
for those genres.